# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'auto'
    labels: [ 'dependencies' ]
    commit-message:
      ## prefix maximum string length of 15
      prefix: 'composer'
      include: 'scope'
    open-pull-requests-limit: 999

  - package-ecosystem: 'composer'
    directories:
    - '/tools/composer-normalize'
    - '/tools/composer-require-checker'
    - '/tools/composer-unused'
    - '/tools/php-cs-fixer'
    - '/tools/psalm'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'auto'
    labels: [ 'dependencies', 'tools' ]
    commit-message:
      ## prefix maximum string length of 15
      prefix: 'tools'
      include: 'scope'
    open-pull-requests-limit: 999

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels: [ 'dependencies', 'CI' ]
    commit-message:
      ## prefix maximum string length of 15
      prefix: 'gh-actions'
      include: 'scope'
    open-pull-requests-limit: 999
